l_braz_por:
 dmm_mod_333: "$shroud_rising_settings.1.name$"
 edict_shroud_rising_settings: "(MOD MENU) §H$shroud_rising_settings.1.name$§!"
 edict_shroud_rising_settings_desc: "Open the current settings for §MShroud Rising§!."
 shroud_rising_settings.1.a: "$FE_DIFFICULTY$ $SETTINGS$"
 shroud_rising_settings.1.a.tooltip: "$DIFFICULTY_ADJUSTED_AI_MODIFIERS$.\nAdjust the difficulty settings of the mod."
 shroud_rising_settings.1.b.tooltip: "Close the menu."
 shroud_rising_settings.1.c: "For $OUTLINER_FALLEN_EMPIRES$ §G$ON$§!"
 shroud_rising_settings.1.c.tooltip: "$shroud_rising_2_poi$ spawns for $OUTLINER_FALLEN_EMPIRES$"
 shroud_rising_settings.1.d: "For $OUTLINER_FALLEN_EMPIRES$ §R$OFF$§!"
 shroud_rising_settings.1.d.tooltip: "$shroud_rising_2_poi$ spawns §RNOT§! for $OUTLINER_FALLEN_EMPIRES$"
 shroud_rising_settings.1.desc: "Select an option below to adjust your §MShroud Rising§! experience. If your difficulty settings are §L$DIFFICULTY_CAPTAIN$§! or above, it is recommended to play at §P2x§! or higher.\n\nThese settings can be opened at any point during your playthrough through the edict menu."
 shroud_rising_settings.1.name: "§MShroud Rising $SETTINGS$§!"
 shroud_rising_settings.12.a.tooltip: "There will be a 100% chance the $sc_eye_of_terror$ crisis chain will occur."
 shroud_rising_settings.12.b.tooltip: "Every year there will be a 75% chance the $sc_eye_of_terror$ crisis chain will occur."
 shroud_rising_settings.12.c.tooltip: "Every year there will be a 50% chance the $sc_eye_of_terror$ crisis chain will occur."
 shroud_rising_settings.12.d.tooltip: "Every year there will be 25% chance the $sc_eye_of_terror$ crisis chain will occur."
 shroud_rising_settings.12.desc: "Choose the likelihood of the §MEye of Terror§! crisis chain occuring. The choices represent an overall yearly chance of triggering the crisis once the requirements have been fulfilled.\n\n§RYou will not be able to change this after the game starts.§!\n\nTo spawn, it must be midgame and the crisis requires at least one non-robotic/non-gestalt Fallen Empire or an AI empire with psionic main species."
 shroud_rising_settings.12.e: "5%"
 shroud_rising_settings.12.e.tooltip: "Every year there will be a 5% chance the $sc_eye_of_terror$ crisis chain will occur."
 shroud_rising_settings.12.f: "§LDisabled§!"
 shroud_rising_settings.12.f.tooltip: "The crisis will be disabled from spawning naturally, but you can always trigger it manually if you wish.\n\nCheck the mod page for more specific instructions."
 shroud_rising_settings.2.0.desc: "Current selection: $shroud_rising_settings.default$"
 shroud_rising_settings.2.1.desc: "Current selection: $shroud_rising_settings.2.g$"
 shroud_rising_settings.2.10.desc: "Current selection: $shroud_rising_settings.2.b$\n\n'§TMay the force be with you.§!'"
 shroud_rising_settings.2.2.desc: "Current selection: $shroud_rising_settings.2.f$"
 shroud_rising_settings.2.25.desc: "Current selection: $shroud_rising_settings.2.a$\n\n'§TWhat drugs did you take today?§!'"
 shroud_rising_settings.2.3.desc: "Current selection: $shroud_rising_settings.2.e$"
 shroud_rising_settings.2.4.desc: "Current selection: $shroud_rising_settings.2.d$"
 shroud_rising_settings.2.5.desc: "Current selection: $shroud_rising_settings.2.c$"
 shroud_rising_settings.2.a: "§P25x§!"
 shroud_rising_settings.2.b: "§P10x§!"
 shroud_rising_settings.2.c: "§P5x§!"
 shroud_rising_settings.2.d: "§P4x§!"
 shroud_rising_settings.2.desc: "Select the overall strength £military_power£ of the §MShroud Rising§! crisis, this will affect enemy spawns that emerge from Rifts, §MThe Eye of Terror§! and other related events.\n\nThis setting can be changed at any time throughout your playthrough and is independent of the vanilla crisis difficulty strength.\n\n"
 shroud_rising_settings.2.e: "§P3x§!"
 shroud_rising_settings.2.f: "§P2x§!"
 shroud_rising_settings.2.g: "§P1.5x§!"
 shroud_rising_settings.2.h: "Return to Main Menu"
 shroud_rising_settings.default: "§L$DEFAULT_GENDER$§!"
 sr_difficulty_1: "$paragon.5265.c$ x1.5"
 sr_difficulty_10: "$paragon.5265.c$ x10"
 sr_difficulty_2: "$paragon.5265.c$ x2"
 sr_difficulty_25: "$paragon.5265.c$ x25"
 sr_difficulty_3: "$paragon.5265.c$ x3"
 sr_difficulty_4: "$paragon.5265.c$ x4"
 sr_difficulty_5: "$paragon.5265.c$ x5"
