l_simp_chinese:
 dmm_mod_333: "$shroud_rising_settings.12.name$"
 edict_shroud_rising_settings: "[MOD MENU]虚境崛起设置"
 edict_shroud_rising_settings_desc: "打开虚境崛起的当前设置。"
 shroud_rising_settings.1.a: "难度设置"
 shroud_rising_settings.1.a.tooltip: "调整模组的难度设置。"
 shroud_rising_settings.1.b.tooltip: "关闭菜单。"
 shroud_rising_settings.1.c: "$ON$ $OUTLINER_FALLEN_EMPIRES$"
 shroud_rising_settings.1.c.tooltip: "$shroud_rising_2_poi$ spawns for $OUTLINER_FALLEN_EMPIRES$"
 shroud_rising_settings.1.d: "§R$OFF$ $OUTLINER_FALLEN_EMPIRES$§!"
 shroud_rising_settings.1.d.tooltip: "$shroud_rising_2_poi$ spawns §RNOT§! for $OUTLINER_FALLEN_EMPIRES$"
 shroud_rising_settings.1.desc: "选择下面的一个选项来调整你的虚境崛起体验。\n\n这些设置可以在你游戏过程中的任何时候通过法令菜单打开。"
 shroud_rising_settings.1.name: "§MShroud Rising $SETTINGS$§!"
 shroud_rising_settings.12.a.tooltip: "将有100%的概率触发恐惧之眼危机事件链。"
 shroud_rising_settings.12.b.tooltip: "将有75%的概率触发恐惧之眼危机事件链。"
 shroud_rising_settings.12.c.tooltip: "将有50%的概率触发恐惧之眼危机事件链。"
 shroud_rising_settings.12.d.tooltip: "将有25%的概率触发恐惧之眼危机事件链。"
 shroud_rising_settings.12.desc: "选择§M恐惧之眼§!危机事件链发生的可能性。这些选择代表了满足要求后触发危机的概率。\n\n§R在游戏开始后，你将无法更改这个设置。§!\n\n要产生此危机，游戏中需要至少有一个非机械/非格式塔政体的堕落帝国或一个主流物种有灵能特质的AI国家。"
 shroud_rising_settings.12.e: "5%"
 shroud_rising_settings.12.e.tooltip: "将有5%的概率触发恐惧之眼危机事件链。"
 shroud_rising_settings.12.f: "§L禁用§!"
 shroud_rising_settings.12.f.tooltip: "此危机将不会自动产生，但是你可以手动触发它。\n\n请查看模组页面以了解更多具体说明。"
 shroud_rising_settings.2.0.desc: "Current selection: $shroud_rising_settings.default$"
 shroud_rising_settings.2.1.desc: "选择虚境崛起危机的整体强度£military_power£，这将影响裂隙、恐惧之眼与其他事件中刷新的敌人难度。\n\n在整个游戏过程中，你可以随时修改这个设置，并且该设置与游戏本体的危机强度无关。\n\n当前选择：§L默认§!"
 shroud_rising_settings.2.10.desc: "选择虚境崛起危机的整体强度£military_power£，这将影响裂隙、恐惧之眼与其他事件中刷新的敌人难度。\n\n在整个游戏过程中，你可以随时修改这个设置，并且该设置与游戏本体的危机强度无关。\n\n当前选择：§P10x§!\n\n“§T愿原力与你同在。”"
 shroud_rising_settings.2.2.desc: "选择虚境崛起危机的整体强度£military_power£，这将影响裂隙、恐惧之眼与其他事件中刷新的敌人难度。\n\n在整个游戏过程中，你可以随时修改这个设置，并且该设置与游戏本体的危机强度无关。\n\n当前选择：§P2x§!"
 shroud_rising_settings.2.25.desc: "选择虚境崛起危机的整体强度£military_power£，这将影响裂隙、恐惧之眼与其他事件中刷新的敌人难度。\n\n在整个游戏过程中，你可以随时修改这个设置，并且该设置与游戏本体的危机强度无关。\n\n当前选择：§P25x§!\n\n“§T好运。”"
 shroud_rising_settings.2.3.desc: "选择虚境崛起危机的整体强度£military_power£，这将影响裂隙、恐惧之眼与其他事件中刷新的敌人难度。\n\n在整个游戏过程中，你可以随时修改这个设置，并且该设置与游戏本体的危机强度无关。\n\n当前选择：§P3x§!"
 shroud_rising_settings.2.4.desc: "选择虚境崛起危机的整体强度£military_power£，这将影响裂隙、恐惧之眼与其他事件中刷新的敌人难度。\n\n在整个游戏过程中，你可以随时修改这个设置，并且该设置与游戏本体的危机强度无关。\n\n当前选择：§P4x§!"
 shroud_rising_settings.2.5.desc: "选择虚境崛起危机的整体强度£military_power£，这将影响裂隙、恐惧之眼与其他事件中刷新的敌人难度。\n\n在整个游戏过程中，你可以随时修改这个设置，并且该设置与游戏本体的危机强度无关。\n\n当前选择：§P5x§!"
 shroud_rising_settings.2.a: "§RInsane§! §P25x§!"
 shroud_rising_settings.2.b: "§P10x§!"
 shroud_rising_settings.2.c: "§P5x§!"
 shroud_rising_settings.2.d: "§P4x§!"
 shroud_rising_settings.2.desc: "Select the overall strength £military_power£ of the §MShroud Rising§! crisis, this will affect enemy spawns that emerge from Rifts, §MThe Eye of Terror§! and other related events.\n\nThis setting can be changed at any time throughout your playthrough and is independent of the vanilla crisis difficulty strength.\n\n"
 shroud_rising_settings.2.e: "§P3x§!"
 shroud_rising_settings.2.f: "§P2x§!"
 shroud_rising_settings.2.g: "§L默认难度§!"
 shroud_rising_settings.2.h: "返回主菜单"
 shroud_rising_settings.default: "§L$DEFAULT_GENDER$§!"
 sr_difficulty_1: "$paragon.5265.c$ x1.5"
 sr_difficulty_10: "10倍强度"
 sr_difficulty_2: "2倍强度"
 sr_difficulty_25: "25倍强度"
 sr_difficulty_3: "3倍强度"
 sr_difficulty_4: "4倍强度"
 sr_difficulty_5: "5倍强度"
